version: '3.0'
services:
  server:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
      - "3000:3000"
    tty: true
    restart: always
    volumes:
      - app_data:/project
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: membership
      MYSQL_USER: wonhoe
      MYSQL_PASSWORD: test123
    ports:
      - "3307:3306"
    volumes:
      - ./db_volume/conf.d:/etc/mysql/conf.d 
      - ./db_volume/mysql:/var/lib/mysql  
volumes:
  app_data:
    driver: local
    driver_opts: 
      type: none
      device: /Users/happydev00/myWorkspace/nodejsProj01
      o: bind

